site_name: complyscribe
site_description: Documentation for complyscribe.
repo_name: complyscribe 
repo_url: https://github.com/complytime/complyscribe/

theme:
  name: material
  language: en
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    

markdown_extensions:
  - md_in_html
  - toc:
      toc_depth: 2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; Copyright 2023 Red Hat, Inc.</a>

plugins:
  - include-markdown

nav:
- Overview: 
  - QuickStart: index.md
  - Architecture:
    - Diagrams: architecture/diagrams/c4.md
- Tutorials:
  - GitHub: tutorials/github.md
  - Authoring: tutorials/authoring.md
  - Sync CaC to OSCAL: tutorials/sync-cac-content.md
  - Sync OSCAL to CaC: tutorials/sync-oscal-content.md
  - Authoring: tutorials/authoring.md
- Troubleshooting: troubleshooting.md
- Contributing: contributing.md


