---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-ci
  cancel-in-progress: true

jobs:
  megalinter:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@e08c2b05e3dbc40af4c23f41172ef1e068a7d651 # v8.8.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  project_checks:
    name: Run project checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up poetry and install
        uses: ./.github/actions/setup-poetry

      - name: Pre-commit install
        run: make pre-commit

      - name: Run linting checks
        run: make lint

      - name: Run security checks
        run: make security-check

      - name: Check dependencies
        run: make dep-cve-check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ]
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up poetry and install
        uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: make test

  e2e-test:
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/e2e-testing

  test-integration:
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/test-integration
