---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-ci
  cancel-in-progress: true

jobs:
  check-changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      code_changed: ${{ steps.detect.outputs.code_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4

      - name: Detect changes in Python files
        id: detect
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          if git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} | grep -q '\.py$'; then
            echo "code_changed=true" >> $GITHUB_OUTPUT
          else
            echo "code_changed=false" >> $GITHUB_OUTPUT
          fi

  megalinter:
    name: Run linters
    needs: check-changes
    if: needs.check-changes.outputs.code_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4

      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@146333030da68e2e58c6ff826633824fabe01eaf # pin@v7
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  project_checks:
    name: Run project checks
    needs: check-changes
    if: needs.check-changes.outputs.code_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4

      - name: Set up poetry and install
        uses: ./.github/actions/setup-poetry

      - name: Pre-commit install
        run: make pre-commit

      - name: Run linting checks
        run: make lint

      - name: Run security checks
        run: make security-check

      - name: Check dependencies
        run: make dep-cve-check

  test:
    name: Run unit tests with different Python versions
    if: needs.check-changes.outputs.code_changed == 'true'
    needs: check-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4

      - name: Set up poetry and install
        uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: make test

  e2e-test:
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4
      - uses: ./.github/actions/e2e-testing

  test-integration:
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4
      - uses: ./.github/actions/test-integration
