name: publish-docs
on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

permissions:
  contents: write

jobs:
  gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: '3.11'
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material mkdocs-include-markdown-plugin
      - run: mkdocs gh-deploy --force
