name: publish-docs
on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

permissions:
  contents: write

jobs:
  gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55  # pin@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # pin@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material markdown-include
      - run: mkdocs gh-deploy --force
